language: r
cache: packages
sudo: false
warnings_are_errors: false

addons:
  apt:
    update: true
    packages:
      - libudunits2-0
      - libudunits2-dev
      - libgdal-dev

r:
  - release
  - devel

r_packages:
  - tidyverse
  - osmdata

notifications:
  email:
    on_success: change
    on_failure: change