language: r
cache: packages
sudo: false
warnings_are_errors: false

r:
  - release
  - devel

r_packages:
  - tidyverse
  - osmdata

notifications:
  email:
    on_success: change
    on_failure: change